name: Manual Trigger with Dropdown and Checklist

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development

      feature_flag:
        description: 'Enable new feature?'
        required: true
        type: boolean
        default: false

      additional_tests:
        description: 'Select additional tests to run (check all that apply)'
        required: false
        default: 'test1, test2'

jobs:
  demo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Display Inputs
        run: |
          echo "Environment selected: ${{ github.event.inputs.environment }}"
          echo "Feature flag enabled: ${{ github.event.inputs.feature_flag }}"
          echo "Additional tests: ${{ github.event.inputs.additional_tests }}"
